### ISSUE TITLE
CRLF injection

### ISSUE THREAD

**Issue by chadwhitacre** [gratipay/security-qf35us#1]
https://gratipay.freshdesk.com/helpdesk/tickets/2305

> == CRLF Injection (Chrome, Internet Explorer) ==
> http://gratipay.com/%0dSet-Cookie:csrf_token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx;
> 
> Response:
> Location: https://gratipay.com/\r
> Set-Cookie:csrf_token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx;\r\n

**Comment by chadwhitacre** [comment]
Really it's header injection:

```
$ curl -I http://localhost:8537/%0dFoo:%20Bar
HTTP/1.1 302 Found
Server: gunicorn/18.0
Date: Mon, 29 Jun 2015 13:15:41 GMT
Connection: close
Transfer-Encoding: chunked
X-Gratipay-Version: 1860
X-Frame-Options: SAMEORIGIN
Foo: Bar/ /
Set-Cookie: csrf_token=[]; expires=Mon, 06 Jul 2015 13:15:41 GMT; Path=/
Cache-Control: no-cache

$
```

**Comment by chadwhitacre** [comment]
I believe the bug is in how we handle redirects.

**Comment by chadwhitacre** [comment]
I put a `set_trace` in [`aspen.http.Request.redirect`](https://github.com/gratipay/aspen-python/blob/0.37/aspen/http/request.py#L336-L349) and I don't hit it! Following up on https://github.com/gratipay/gratipay.com/issues/2138#issuecomment-37618916:

> Yeah, looks like we have some code that manually performs redirection.

**Comment by chadwhitacre** [comment]
I'm finding four places outside of `Request.redirect` where we construct redirect responses:
- [the dispatcher](https://github.com/gratipay/aspen-python/blob/0.37/aspen/dispatcher.py#L306-L318), [twice](https://github.com/gratipay/aspen-python/blob/0.37/aspen/dispatcher.py#L344-L348)
- [`canonicalize`](https://github.com/gratipay/gratipay.com/blob/1860/gratipay/utils/__init__.py#L44-L53), which is called from `get_{participant,team}` to redirect, e.g., `/~Foo/` to `/~foo/`
  - not to be confused with [`canonize`](https://github.com/gratipay/gratipay.com/blob/1860/gratipay/__init__.py#L57-L84), which acts on the netloc to redirect, e.g., `http://www.gittip.org/` to `https://gratipay.com/`
- the [`Response.redirect`](https://github.com/gratipay/gratipay.com/blob/1860/gratipay/main.py#L139-L142) monkey-patch
- [elsewhere JSON endpoints](https://github.com/gratipay/gratipay.com/blob/1860/www/on/%25platform/%25user_name/%25endpoint.json.spt#L34-L40)

**Comment by chadwhitacre** [comment]
> Really it's header injection:

Sorry, I misread "CRLF injection" in the title as "CSRF injection."

**Comment by chadwhitacre** [comment]
For the test case above, we're hitting the second dispatcher redirect (to trailing slash).

**Comment by chadwhitacre** [comment]
Okay! What's the best fix?

**Comment by chadwhitacre** [comment]
Seems like a safe, low-level place to fix this bug would be in [`Response.__init__`](https://github.com/gratipay/aspen-python/blob/0.37/aspen/http/response.py#L86-L87) or possibly even in `Mapping.{`[`__set_item__`](https://github.com/gratipay/aspen-python/blob/0.37/aspen/http/mapping.py#L35-L38)`,`[`add`](https://github.com/gratipay/aspen-python/blob/0.37/aspen/http/mapping.py#L76-L82)`}`. Note that the latter is shared with the `body` parsing machinery, where we don't want to clobber `\r`.

**Comment by chadwhitacre** [comment]
Or is now the time to migrate Aspen to Werkzeug? Cf. https://github.com/gratipay/aspen-python/issues/357.

**Comment by chadwhitacre** [comment]
Here's [Werkzeug's protection against this](https://github.com/mitsuhiko/werkzeug/blob/c82e82ace368fefc0581bc0a700f1219cc4c79ca/werkzeug/datastructures.py#L1113-L1115).

**Comment by chadwhitacre** [comment]
Hah! We already have [`LF` injection protection](https://github.com/gratipay/aspen-python/blob/0.37/aspen/http/baseheaders.py#L56-L65). We just need to add `CR` injection protection. ;-)

The other limitation with our current implementation is that adding a second value for the same header [doesn't go through `BaseHeaders.__setitem__`](https://github.com/gratipay/aspen-python/blob/0.37/aspen/http/mapping.py#L80).

**Comment by chadwhitacre** [comment]
Ping @pjz.

**Comment by chadwhitacre** [comment]
@pjz I just added you to the Gratipay security team so you can help me land the fix for this. You available? :)

**Comment by chadwhitacre** [comment]
Fixed in [Aspen 0.39](https://github.com/gratipay/aspen-python/blob/master/Changelog.md#039---released-mon-jun-29-2015-by-whit537).

**Comment by techtonik** [comment]
Niiice. Did you find any real threats for CRLF injection in GP?

**Comment by chadwhitacre** [comment]
Fix deployed in https://github.com/gratipay/gratipay.com/pull/3588, but https://github.com/gratipay/gratipay.com/issues/3594 is causing a 500. Still considering this fixed tho:

```
$ curl -I http://gratipay.com/%0dSet-Cookie:csrf_token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx;
HTTP/1.1 500 Internal Server Error
Connection: keep-alive
Server: gunicorn/18.0
Date: Thu, 02 Jul 2015 21:46:59 GMT
Transfer-Encoding: chunked
Via: 1.1 vegur

$
```

**Comment by chadwhitacre** [comment]
@techtonik Yes: https://github.com/gratipay/security-flh0cu/issues/1.

**Comment by chadwhitacre** [comment]
To: researcher

> The CRLF Injection and CSRF Protection Bypass bugs should be fixed now. Please confirm.
> 
> I've added you to our legacy Halls of Fame for Aspen (for the CRLF injection) and Gratipay (for the CSRF protection bypass):
> 
> http://aspen.io/security.txt
> https://gratipay.com/about/security/hall-of-fame
> 
> We've now migrated our security program [to HackerOne](https://hackerone.com/gratipay). If you would like acknowledgement on HackerOne feel free to re-file the bugs there and I will resolve them.
> 
> Thanks for the reports! :-)

**Comment by chadwhitacre** [comment]
https://hackerone.com/reports/79552
